
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  issues:
    types: [opened]
jobs:
  titlePrefixCheck:
    runs-on: ubuntu-latest
    steps:
      - if: true
        name: Close Issue
        uses: peter-evans/close-issue@v1
        with:
          comment: |
            Issue title must start with 'ABC-'.
            Auto-closing this issue.
